export function DeskUnconfigured() {
  return <div className="desk">
    <div className="desk-masthead"><div><p className="edition">ARCLET FINANCIAL DESK / ARC TESTNET</p><h1>THE MANDATE</h1></div><div className="masthead-note">Rules you approve. Facts we record.<br />No real monetary value.</div></div>
    <div className="desk-grid">
      <section className="chat-desk" aria-labelledby="chat-heading"><div className="section-heading"><div><p className="kicker">Correspondence</p><h2 id="chat-heading">Ask the desk</h2></div></div><div className="transcript"><article className="message message-agent"><p className="message-byline">ARCLET / SETUP NOTE</p><p>Configure Privy and server verification before signing in. Arclet never substitutes a mock identity or live trade.</p></article></div><div className="composer"><label htmlFor="setup-instruction">Instruction</label><textarea id="setup-instruction" rows={4} disabled placeholder="Setup is required before the desk can accept a request." /><div className="composer-actions"><button disabled>Ask Arclet</button></div></div><div className="desk-controls"><button className="pause-control" disabled>Pause mandate</button><span>No mandate exists. Controls remain deterministic when configured.</span><button className="text-button" disabled>Prepare withdrawal</button></div></section>
      <aside className="agent-desk" aria-labelledby="agent-desk-heading"><div className="section-heading"><div><p className="kicker">Agent desk</p><h2 id="agent-desk-heading">Decision tape</h2></div><output className="desk-status">Needs setup</output></div><section className="tape-block"><h3>Latest rationale</h3><p>No decision has been recorded.</p></section><section className="tape-block"><h3>Checked facts</h3><p>Graph health, mandate limits, wallet balances, quote freshness, and execution state appear only after authenticated evaluations.</p></section><section className="tape-block"><h3>Source evidence</h3><p>No verified Graph deployment or pool has been selected.</p></section></aside>
      <section className="ledger-section" aria-labelledby="ledger-heading"><div className="section-heading"><div><p className="kicker">Recorded actions</p><h2 id="ledger-heading">Trade ledger</h2></div><span className="ledger-count">0 entries</span></div><div className="ledger-empty">No HOLD, quote, submission, receipt, failed, or unknown state has been recorded.</div></section>
      <section className="desk-section chart-section" aria-labelledby="portfolio-heading"><div className="section-heading"><div><p className="kicker">Ledger line</p><h2 id="portfolio-heading">Trading USDC</h2></div><p className="measure">Persisted ERC-20 USDC view</p></div><div className="chart-frame"><div className="chart-y-label top">USDC</div><div className="chart-y-label bottom">0</div><div className="chart-empty"><strong>No balance history yet.</strong><span>Arclet will draw this line only after coherent wallet snapshots are persisted.</span></div></div><div className="chart-caption"><span>No recorded balance</span><span>Not profit or performance. It excludes unverified asset valuation.</span></div></section>
    </div>
  </div>;
}
